### ISSUE TITLE
[Bug] Clipping occurs when filter is applied to scenes

### ISSUE THREAD

**Issue by chocobclyn** [TheJollyBeardo/OBS_RTX_SuperResolution#5]
Currently the plugin also resizes the scene and clips beyond the canvas instead of stretching the output within the canvas. Applying SuperResolution would help improve overall scene's  video quality, while maintaining low resource consumption.

Recreating problem:
1. Create and populate scene
2. Apply SCENE filter>SuperResolution
3. Apply 1.5x or 2.x scaling

**Comment by Bemjo** [comment]
@chocobclyn This is less of a bug, and more of a use case error, and not something I am inclined to look into fixing. I highly recommend not trying to apply this to a scene itself, and then view the scene itself.

The recommended usage of your use case is either to:
- Apply the filter to the source within the scene itself
- Apply the filter to a scene source placed within another scene, or better yet use the [Source Clone plugin](https://github.com/exeldro/obs-source-clone) and apply the filter to that source that is cloning the scene.

If either of these options are not suitable because of resource consumption issues, I would highly recommend you take a hard look at your scenes and how you're composing things, as the resource increase from either of these is literally zero if it's only one source in your scene, or next to zero as you'd be making a new scene and placing a single source within.

In both cases, this would require you to set the transformation sizing to whatever you applied the filter to, and let OBS handle it because it's already handling it.

In ANY case regardless, this requires your canvas to be the size you require, and this is something you would manually set inside the OBS settings, or to resize the source back down to your canvas size.

**Comment by chocobclyn** [comment]
I appreciate the input and the suggestion for a different approach. Instead of applying the filter directly to the scene itself, I've created a scene source and placed them in a separate scene.
![image](https://github.com/Bemjo/OBS-RTX-SuperResolution/assets/144403383/921d5f16-66b7-4634-be53-560d1a485c96)
